### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/readme#1]
Add CLI flags for:
- [ ] verbose
- [ ] force overwrite existing readme
- [ ] add build badge
- [ ] just output build badge
